{
  "lastUpdate": 1784694298490,
  "repoUrl": "https://github.com/autumn-foundation/AletheiaDB",
  "entries": {
    "AletheiaDB Benchmarks": [
      {
        "commit": {
          "author": {
            "email": "markmasterson@gmail.com",
            "name": "Mark Masterson",
            "username": "madmax983"
          },
          "committer": {
            "email": "noreply@github.com",
            "name": "GitHub",
            "username": "web-flow"
          },
          "distinct": true,
          "id": "3c75c0741f9d743979f826860a49d1c56a30c803",
          "message": "docs: refresh stale 0.1 install-snippet versions to 0.2; fix Cargo repository URL (#3773)\n\n## What & Why\n\nText-only doc-comment + manifest cleanup. No logic changes.\n\n**Before**\n\n- Several module-level `//!` doc-comments show an install snippet pinned\nto the old crate version:\n`aletheiadb = { version = \"0.1\", features = [...] }`. The crate is\nactually published at `0.2.0`, so anyone copy-pasting these snippets\npulls a stale version.\n- `Cargo.toml`'s `repository` still points at the pre-transfer org:\n`https://github.com/madmax983/AletheiaDB`.\n\n**After**\n\n- All install-snippet doc-comments read `version = \"0.2\"`, matching the\npublished `0.2.0` crate.\n- `Cargo.toml` `repository` now points at\n`https://github.com/autumn-foundation/AletheiaDB`.\n\n## How (files touched)\n\nSeven `version = \"0.1\"` install-snippet doc-comments bumped to `0.2`:\n\n- `src/sql/mod.rs`\n- `src/semantic_search/mod.rs`\n- `src/experimental/mod.rs` (two snippets: `nova` and\n`semantic-temporal`)\n- `src/storage/sharding/rpc_client.rs`\n- `src/cypher/mod.rs`\n- `src/experimental/reasoning/prophet.rs` (commented-out `//! //\naletheiadb = ...` example)\n\nPlus `Cargo.toml`: `repository` URL updated. `version = \"0.2.0\"` left\nuntouched.\n\n**Count note:** the original scope flagged 6 install snippets. I also\nupdated the commented-out example in\n`src/experimental/reasoning/prophet.rs` for consistency, bringing the\ntotal to 7. Disclosing this deliberately.\n\nDeliberately **not** touched: the `#[deprecated(since = \"0.1.0\", ...)]`\nattributes, the float `0.1` in `src/storage/migration.rs`, and the\nhistorical \"graduated ... in 0.1\" note in `src/lib.rs`. A final `grep\n-rn 'version = \"0\\.1\"' src/` returns zero install-snippet matches.\n\n## Gate evidence\n\n- `cargo fmt --all -- --check` — clean (exit 0)\n- `CARGO_INCREMENTAL=0 cargo clippy --no-default-features --all-targets\n-- -D warnings` — pass (exit 0)\n- `CARGO_INCREMENTAL=0 cargo clippy --features\nconfig-toml,mcp-server,sharding-rpc,simulation --all-targets -- -D\nwarnings` — pass (exit 0)\n- `CARGO_INCREMENTAL=0 cargo check --no-default-features` — pass (exit\n0)\n\nFull test suite intentionally skipped: this is a doc-comment + manifest\ntext change with no logic, so it cannot alter runtime behavior.\n\n\n---\n_Generated by [Claude\nCode](https://claude.ai/code/session_01SoU9E2nmLDhDh9bYJ6r6bV)_\n\nCo-authored-by: Claude <noreply@anthropic.com>",
          "timestamp": "2026-07-21T23:06:18-05:00",
          "tree_id": "e06a5bd874e76c2c033acc139f3182ddb0808c49",
          "url": "https://github.com/autumn-foundation/AletheiaDB/commit/3c75c0741f9d743979f826860a49d1c56a30c803"
        },
        "date": 1784694298490,
        "tool": "customSmallerIsBetter",
        "benches": [
          {
            "name": "target_3_hop/traverse_three_hops",
            "value": 154.53670107920416,
            "unit": "ns"
          },
          {
            "name": "target_single_hop/traverse_one_hop",
            "value": 18.75359129666914,
            "unit": "ns"
          },
          {
            "name": "target_batch_insertion/insert_1000_edges",
            "value": 483163.01717031206,
            "unit": "ns"
          },
          {
            "name": "target_time_travel/worst_case_9_deltas",
            "value": 184.64780322877502,
            "unit": "ns"
          },
          {
            "name": "target_time_travel/at_anchor",
            "value": 176.06411393526193,
            "unit": "ns"
          },
          {
            "name": "target_time_travel/with_5_deltas",
            "value": 173.37360861572154,
            "unit": "ns"
          }
        ]
      }
    ]
  }
}