{
  "lastUpdate": 1789395884376,
  "repoUrl": "https://github.com/autumn-foundation/AletheiaDB",
  "entries": {
    "AletheiaDB Benchmarks": [
      {
        "commit": {
          "author": {
            "email": "markmasterson@gmail.com",
            "name": "Mark Masterson",
            "username": "madmax983"
          },
          "committer": {
            "email": "noreply@github.com",
            "name": "GitHub",
            "username": "web-flow"
          },
          "distinct": true,
          "id": "aef5abe74c91a0d3f84956f62f16197cb7d75dec",
          "message": "Bolt: add vector search (HNSW find_similar) workload benchmark (no fix) (#3834)\n\n## Summary\n\n- Adds `examples/bolt_vector_workload.rs`, a deterministic,\npublic-API-driven benchmark for `AletheiaDB`'s vector similarity search\npath: enable a vector index, create 2,000 nodes each carrying a 128-dim\nembedding (auto-indexed through the normal `create_node` write-path\nhook), then issue 500 `similarity_search` (k=10) k-NN queries. Vector\ngeneration uses a fixed-seed `SmallRng` (not `thread_rng`), so the\nembeddings — and therefore the HNSW graph shape and every query's\ncandidate set — are bit-identical run to run, keeping instruction counts\nreproducible.\n- **No `src/` changes.** This PR ships a benchmark harness only — no\nperformance fix.\n\n## Why no fix\n\nProfiling this harness under `valgrind --tool=callgrind` (2,000 nodes ×\n128 dims, 500 k-NN queries) found **84.27%** of total instructions\nattributed directly to the vendored `usearch`/`numkong` HNSW library\n(`nk_angular_f32_haswell`, a hand-written AVX2/FMA SIMD cosine-distance\nkernel, plus `usearch::index_gt::search_to_insert_`, the library's own\nHNSW beam-search graph traversal), and another **5.83%** in libc\n`memset`/`memcpy` driven by `usearch`'s own buffer management — **90.1%\ncombined**. This is inherent work inside a third-party, hardware-tuned\nC++ ANN library, not AletheiaDB Rust code, and not something a \"smallest\nchange that moves the counter\" patch can touch.\n\nThe remaining ~10% is fragmented across hundreds of AletheiaDB-authored\nlines (WAL append, `DashMap` ops, `PropertyMapBuilder`, hashing,\ntransaction commit) — the single largest is 0.18% of the profile.\nNothing clears this process's 5% impact floor.\n\nFull writeup — the profile breakdown, DHAT allocation summary, and notes\non the levers that *would* move this number (quantization,\n`ef_search`/`m` tuning, call batching) but need a human call rather than\nan unsupervised patch — is in #3833.\n\n## What this PR is for\n\nLanding the harness now means the profile and the negative result above\nare reproducible by anyone who checks out this branch, without redoing\nthe setup, and gives a starting point for whoever picks up quantization\ntuning or a `usearch` version bump evaluation.\n\n## Test plan\n\n- [x] `cargo build --profile bench --example bolt_vector_workload`\nsucceeds\n- [x] Native run produces a deterministic `sink=...` line, unchanged\nacross the two builds in this session\n- [x] `cargo fmt --all -- --check` — clean\n- [x] `cargo clippy --example bolt_vector_workload --all-features -- -D\nwarnings` — clean, no warnings\n- Reproduce the profile:\n  ```\n  cargo build --profile bench --example bolt_vector_workload\n  BOLT_NODES=2000 BOLT_DIMENSIONS=128 BOLT_K=10 BOLT_QUERY_ITERS=500 \\\n    valgrind --tool=callgrind --callgrind-out-file=/tmp/cg.out -- \\\n    target/release/examples/bolt_vector_workload\n  callgrind_annotate --threshold=90 /tmp/cg.out | head -40\n  ```\n\nCloses/references: #3833\n\n🤖 Generated with [Claude Code](https://claude.com/claude-code)\n\nhttps://claude.ai/code/session_01QgttZHHKVEevXRmPVvvxJE\n\n\n---\n_Generated by [Claude\nCode](https://claude.ai/code/session_01QgttZHHKVEevXRmPVvvxJE)_\n\n---------\n\nCo-authored-by: Claude <noreply@anthropic.com>",
          "timestamp": "2026-09-14T09:14:22-05:00",
          "tree_id": "d74c45b20c0557e13d8c4a65d3df2536a388316c",
          "url": "https://github.com/autumn-foundation/AletheiaDB/commit/aef5abe74c91a0d3f84956f62f16197cb7d75dec"
        },
        "date": 1789395884375,
        "tool": "customSmallerIsBetter",
        "benches": [
          {
            "name": "target_single_hop/traverse_one_hop",
            "value": 24.6631314391595,
            "unit": "ns"
          },
          {
            "name": "target_3_hop/traverse_three_hops",
            "value": 148.4565054231582,
            "unit": "ns"
          },
          {
            "name": "target_time_travel/with_5_deltas",
            "value": 155.75952961835813,
            "unit": "ns"
          },
          {
            "name": "target_time_travel/worst_case_9_deltas",
            "value": 163.49327935339718,
            "unit": "ns"
          },
          {
            "name": "target_time_travel/at_anchor",
            "value": 156.20773363372368,
            "unit": "ns"
          },
          {
            "name": "target_batch_insertion/insert_1000_edges",
            "value": 460862.5257083876,
            "unit": "ns"
          }
        ]
      }
    ]
  }
}