[package]
name = "aletheiadb-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
tempfile = "3"

[dependencies.aletheiadb]
path = ".."

[[bin]]
name = "wal_segment_metadata_from_bytes"
path = "fuzz_targets/wal_segment_metadata_from_bytes.rs"
test = false
doc = false
bench = false

[[bin]]
name = "aql_parser"
path = "fuzz_targets/aql_parser.rs"
test = false
doc = false
bench = false

[[bin]]
name = "wal_segment_reader_from_bytes"
path = "fuzz_targets/wal_segment_reader_from_bytes.rs"
test = false
doc = false
bench = false

[[bin]]
name = "vector_mappings_from_bytes"
path = "fuzz_targets/vector_mappings_from_bytes.rs"
test = false
doc = false
bench = false

[workspace]
members = ["."]
