#![cfg(feature = "aws-kms")]

use super::{KeyProvider, MasterKey, KeyError};
use async_trait::async_trait;
use std::path::PathBuf;
use std::fs;
use aws_sdk_kms::types::DataKeySpec;
use aws_sdk_kms::primitives::Blob;

/// Abstract interface for KMS operations to enable mocking.
#[async_trait]
pub trait KmsOperations: Send + Sync {
    /// Decrypt the data.
    async fn decrypt(&self, ciphertext: &[u8]) -> Result<Vec<u8>, String>;

    /// Generate a new data key.
    /// Returns (plaintext_key, ciphertext_blob).
    async fn generate_data_key(&self) -> Result<(Vec<u8>, Vec<u8>), String>;
}

use aws_config::BehaviorVersion;

/// Real AWS KMS implementation.
pub struct RealKmsClient {
    client: aws_sdk_kms::Client,
    key_id: String,
}

impl RealKmsClient {
    /// Create a new RealKmsClient.
    pub async fn new(key_id: String, region: Option<String>) -> Self {
        let mut config_loader = aws_config::defaults(BehaviorVersion::latest());
        if let Some(r) = region {
             config_loader = config_loader.region(aws_config::Region::new(r));
        }
        let config = config_loader.load().await;
        let client = aws_sdk_kms::Client::new(&config);

        Self { client, key_id }
    }
}

#[async_trait]
impl KmsOperations for RealKmsClient {
    async fn decrypt(&self, ciphertext: &[u8]) -> Result<Vec<u8>, String> {
        let blob = Blob::new(ciphertext);
        let resp = self.client.decrypt()
            .key_id(&self.key_id) // Optional usually, but good to be explicit
            .ciphertext_blob(blob)
            .send()
            .await
            .map_err(|e| e.to_string())?;

        let plaintext = resp.plaintext.ok_or("No plaintext returned")?;
        Ok(plaintext.into_inner())
    }

    async fn generate_data_key(&self) -> Result<(Vec<u8>, Vec<u8>), String> {
        let resp = self.client.generate_data_key()
            .key_id(&self.key_id)
            .key_spec(DataKeySpec::Aes256)
            .send()
            .await
            .map_err(|e| e.to_string())?;

        let plaintext = resp.plaintext.ok_or("No plaintext returned")?;
        let ciphertext = resp.ciphertext_blob.ok_or("No ciphertext returned")?;

        Ok((plaintext.into_inner(), ciphertext.into_inner()))
    }
}

/// Key provider that uses AWS KMS to manage the master key.
///
/// The master key is generated by KMS (GenerateDataKey) and the *encrypted* version
/// is stored in a local file. At startup, the provider reads the encrypted key
/// and asks KMS to decrypt it.
pub struct AwsKmsProvider {
    ops: Box<dyn KmsOperations>,
    storage_path: PathBuf,
}

impl AwsKmsProvider {
    /// Create a new AwsKmsProvider using the real AWS SDK.
    pub async fn new(key_id: impl Into<String>, region: Option<String>, storage_path: impl Into<PathBuf>) -> Self {
        let ops = RealKmsClient::new(key_id.into(), region).await;
        Self {
            ops: Box::new(ops),
            storage_path: storage_path.into(),
        }
    }

    /// Create a new AwsKmsProvider with a custom backend (e.g. for testing).
    pub fn new_with_ops(ops: Box<dyn KmsOperations>, storage_path: impl Into<PathBuf>) -> Self {
        Self {
            ops,
            storage_path: storage_path.into(),
        }
    }
}

#[async_trait]
impl KeyProvider for AwsKmsProvider {
    async fn get_master_key(&self) -> Result<MasterKey, KeyError> {
        // 1. Check if storage file exists
        if self.storage_path.exists() {
            // Load and decrypt
            let ciphertext = fs::read(&self.storage_path).map_err(|e| {
                KeyError::ConfigError(format!("Failed to read key file: {}", e))
            })?;

            let plaintext = self.ops.decrypt(&ciphertext).await.map_err(|e| {
                KeyError::ProviderError(e)
            })?;

            if plaintext.len() != 32 {
                 // AES-256 is 32 bytes
                 return Err(KeyError::ConfigError("Decrypted key has invalid length".to_string()));
            }

            let mut key = [0u8; 32];
            key.copy_from_slice(&plaintext);

            Ok(MasterKey::new(key, 1))
        } else {
            // Generate new
            let (plaintext, ciphertext) = self.ops.generate_data_key().await.map_err(|e| {
                KeyError::ProviderError(e)
            })?;

             if plaintext.len() != 32 {
                 return Err(KeyError::ConfigError("Generated key has invalid length".to_string()));
            }

            // Save ciphertext
            fs::write(&self.storage_path, &ciphertext).map_err(|e| {
                 KeyError::ConfigError(format!("Failed to write key file: {}", e))
            })?;

            let mut key = [0u8; 32];
            key.copy_from_slice(&plaintext);

            Ok(MasterKey::new(key, 1))
        }
    }

    async fn get_key_version(&self, version: u32) -> Result<MasterKey, KeyError> {
         let key = self.get_master_key().await?;
        if key.version() == version {
            Ok(key)
        } else {
            Err(KeyError::NotFound)
        }
    }

    fn current_version(&self) -> u32 {
        1
    }

    fn name(&self) -> &str {
        "AwsKmsProvider"
    }
}
