"""Type stubs for the native AletheiaDB extension."""

from __future__ import annotations

from datetime import datetime
from typing import Any, ClassVar

__version__: str

class Node:
    id: int
    label: str
    @property
    def properties(self) -> dict[str, Any]: ...
    def __repr__(self) -> str: ...

class Edge:
    id: int
    source_id: int
    target_id: int
    label: str
    @property
    def properties(self) -> dict[str, Any]: ...
    def __repr__(self) -> str: ...

class DistanceMetric:
    COSINE: ClassVar[DistanceMetric]
    EUCLIDEAN: ClassVar[DistanceMetric]
    DOT_PRODUCT: ClassVar[DistanceMetric]
    def __repr__(self) -> str: ...

class HnswConfig:
    def __init__(
        self,
        dimensions: int,
        metric: DistanceMetric | None = ...,
        m: int | None = ...,
        ef_construction: int | None = ...,
        ef_search: int | None = ...,
    ) -> None: ...
    @property
    def dimensions(self) -> int: ...
    @property
    def metric(self) -> DistanceMetric: ...
    def __repr__(self) -> str: ...

TimestampLike = int | str | datetime | None

class AletheiaDB:
    def __init__(self) -> None: ...
    @staticmethod
    def open(config_path: str) -> AletheiaDB: ...
    # Node CRUD
    def create_node(self, label: str, properties: dict[str, Any] | None = ...) -> int: ...
    def get_node(self, id: int) -> Node: ...
    def update_node(self, id: int, properties: dict[str, Any] | None = ...) -> None: ...
    def delete_node(self, id: int) -> None: ...
    def delete_node_cascade(self, id: int) -> None: ...
    def count_nodes(self) -> int: ...
    def list_nodes(self) -> list[int]: ...
    def nodes_by_label(self, label: str) -> list[int]: ...
    # Edge CRUD
    def create_edge(
        self,
        source: int,
        target: int,
        label: str,
        properties: dict[str, Any] | None = ...,
    ) -> int: ...
    def get_edge(self, id: int) -> Edge: ...
    def update_edge(self, id: int, properties: dict[str, Any] | None = ...) -> None: ...
    def delete_edge(self, id: int) -> None: ...
    def count_edges(self) -> int: ...
    # Adjacency / traversal
    def outgoing_edges(self, node_id: int, label: str | None = ...) -> list[int]: ...
    def incoming_edges(self, node_id: int, label: str | None = ...) -> list[int]: ...
    def out_degree(self, node_id: int) -> int: ...
    def in_degree(self, node_id: int) -> int: ...
    def traverse(
        self,
        start: int,
        label: str | None = ...,
        max_depth: int = ...,
        direction: str = ...,
    ) -> list[dict[str, Any]]: ...
    # Temporal
    def get_node_at_time(
        self,
        id: int,
        valid_time: TimestampLike = ...,
        tx_time: TimestampLike = ...,
    ) -> Node: ...
    def get_edge_at_time(
        self,
        id: int,
        valid_time: TimestampLike = ...,
        tx_time: TimestampLike = ...,
    ) -> Edge: ...
    def node_history(self, id: int) -> list[dict[str, Any]]: ...
    # Query languages
    def execute_cypher(
        self, query: str, params: dict[str, Any] | None = ...
    ) -> list[dict[str, Any]]: ...
    def __repr__(self) -> str: ...

def enable_vector_index(db: AletheiaDB, property: str, config: HnswConfig) -> None: ...
def find_similar(
    db: AletheiaDB,
    query_node_id: int,
    k: int = ...,
    label: str | None = ...,
) -> list[tuple[int, float]]: ...
def find_similar_by_vector(
    db: AletheiaDB,
    embedding: list[float],
    k: int = ...,
    label: str | None = ...,
) -> list[tuple[int, float]]: ...
def execute_aql(db: AletheiaDB, query: str) -> list[dict[str, Any]]: ...

# Exceptions
class AletheiaDBError(Exception): ...
class NodeNotFound(AletheiaDBError): ...
class EdgeNotFound(AletheiaDBError): ...
class InvalidId(AletheiaDBError): ...
class IoError(AletheiaDBError): ...
class TemporalError(AletheiaDBError): ...
class QueryError(AletheiaDBError): ...
class ConfigError(AletheiaDBError): ...
