use crate::core::id::NodeId;
use crate::db::GallifreyDB;
use crate::utils::Result;
use std::collections::HashMap;

/// A semantic region in the graph, defined by a cluster of similar vectors.
#[derive(Debug, Clone)]
pub struct Region {
    /// Unique identifier for the region (0..k).
    pub id: usize,
    /// The centroid vector of this region.
    pub centroid: Vec<f32>,
    /// The nodes that belong to this region.
    pub members: Vec<NodeId>,
}

/// A map of semantic regions generated by the Cartographer.
#[derive(Debug, Clone)]
pub struct RegionMap {
    /// The regions found in the graph.
    pub regions: Vec<Region>,
}

/// The Cartographer is responsible for discovering semantic structure in the graph.
///
/// It uses unsupervised learning (K-Means) to cluster nodes based on their
/// vector embeddings, creating a high-level map of the knowledge graph.
pub struct Cartographer {
    /// Maximum number of iterations for the clustering algorithm.
    pub max_iterations: usize,
    /// Convergence threshold (stop if centroids move less than this).
    pub tolerance: f32,
}

impl Default for Cartographer {
    fn default() -> Self {
        Self {
            max_iterations: 100,
            tolerance: 0.001,
        }
    }
}

impl Cartographer {
    /// Create a new Cartographer with default settings.
    pub fn new() -> Self {
        Self::default()
    }

    /// Generate a semantic map of the graph by clustering nodes.
    ///
    /// This scans the entire graph for nodes with the specified vector property,
    /// then performs K-Means clustering to identify regions.
    ///
    /// # Arguments
    ///
    /// * `db` - The database instance to scan.
    /// * `property_name` - The property containing the vector embeddings.
    /// * `num_regions` - The desired number of regions (k).
    pub fn generate_map(
        &self,
        db: &GallifreyDB,
        property_name: &str,
        num_regions: usize,
    ) -> Result<RegionMap> {
        // 1. Collect all vectors
        let mut points: Vec<(NodeId, Vec<f32>)> = Vec::new();

        // Use scan(None) to iterate over all nodes
        let query = db.query().scan(None).execute(db)?;

        for row_result in query {
            let row = row_result?;
            if let Some(node) = row.entity.as_node() {
                if let Some(vector) = node
                    .get_property(property_name)
                    .and_then(|v| v.as_vector())
                {
                    points.push((node.id, vector.to_vec()));
                }
            }
        }

        if points.is_empty() {
            return Ok(RegionMap { regions: Vec::new() });
        }

        if num_regions == 0 {
             return Ok(RegionMap { regions: Vec::new() });
        }

        let dimensions = points[0].1.len();
        // Validate dimensions
        for (_, p) in &points {
            if p.len() != dimensions {
                 return Err(crate::utils::Error::Vector(
                    crate::utils::error::VectorError::DimensionMismatch {
                        expected: dimensions,
                        actual: p.len(),
                    }
                ));
            }
        }

        // Adjust k if we have fewer points than requested regions
        let k = std::cmp::min(num_regions, points.len());

        // 2. Initialize Centroids (Deterministic: First k points)
        // In a real implementation, we might use K-Means++ or random initialization.
        // For reproducibility and minimal dependencies, we use the first k points.
        let mut centroids: Vec<Vec<f32>> = points
            .iter()
            .take(k)
            .map(|(_, v)| v.clone())
            .collect();

        // 3. K-Means Loop
        let mut assignments: Vec<usize> = vec![0; points.len()];

        for _iteration in 0..self.max_iterations {
            let mut changed = false;
            let mut centroid_sums = vec![vec![0.0; dimensions]; k];
            let mut centroid_counts = vec![0; k];

            // Assignment Step
            for (i, (_, point)) in points.iter().enumerate() {
                let mut best_cluster = 0;
                let mut min_dist = f32::MAX;

                for (cluster_idx, centroid) in centroids.iter().enumerate() {
                    let dist = euclidean_distance(point, centroid);
                    if dist < min_dist {
                        min_dist = dist;
                        best_cluster = cluster_idx;
                    }
                }

                if assignments[i] != best_cluster {
                    assignments[i] = best_cluster;
                    changed = true;
                }

                // Accumulate for update step
                for (d, &val) in point.iter().enumerate() {
                    centroid_sums[best_cluster][d] += val;
                }
                centroid_counts[best_cluster] += 1;
            }

            // Update Step
            let mut max_centroid_move = 0.0;

            for j in 0..k {
                if centroid_counts[j] > 0 {
                    let mut new_centroid = vec![0.0; dimensions];
                    for d in 0..dimensions {
                        new_centroid[d] = centroid_sums[j][d] / centroid_counts[j] as f32;
                    }

                    let move_dist = euclidean_distance(&centroids[j], &new_centroid);
                    if move_dist > max_centroid_move {
                        max_centroid_move = move_dist;
                    }

                    centroids[j] = new_centroid;
                }
            }

            if !changed || max_centroid_move < self.tolerance {
                break;
            }
        }

        // 4. Construct Result
        let mut regions: Vec<Region> = (0..k)
            .map(|id| Region {
                id,
                centroid: centroids[id].clone(),
                members: Vec::new(),
            })
            .collect();

        for (i, (node_id, _)) in points.into_iter().enumerate() {
            let cluster_idx = assignments[i];
            regions[cluster_idx].members.push(node_id);
        }

        Ok(RegionMap { regions })
    }
}

fn euclidean_distance(a: &[f32], b: &[f32]) -> f32 {
    let mut sum = 0.0;
    for (x, y) in a.iter().zip(b.iter()) {
        sum += (x - y).powi(2);
    }
    sum.sqrt()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::core::property::PropertyMapBuilder;
    use crate::db::GallifreyDB;

    #[test]
    fn test_cartographer_simple_clustering() {
        let db = GallifreyDB::new().unwrap();

        // Create 2 clusters of points
        // Cluster A: Around [0, 0]
        let a1 = db.create_node(
            "Point",
            PropertyMapBuilder::new()
                .insert_vector("vec", &[0.1, 0.1])
                .build()
        ).unwrap();
        let a2 = db.create_node(
            "Point",
            PropertyMapBuilder::new()
                .insert_vector("vec", &[0.2, 0.2])
                .build()
        ).unwrap();

        // Cluster B: Around [10, 10]
        let b1 = db.create_node(
            "Point",
            PropertyMapBuilder::new()
                .insert_vector("vec", &[10.1, 10.1])
                .build()
        ).unwrap();
        let b2 = db.create_node(
            "Point",
            PropertyMapBuilder::new()
                .insert_vector("vec", &[10.2, 10.2])
                .build()
        ).unwrap();

        let cartographer = Cartographer::new();
        let map = cartographer.generate_map(&db, "vec", 2).unwrap();

        assert_eq!(map.regions.len(), 2);

        // Find which region contains a1
        let region_a_idx = map.regions.iter().position(|r| r.members.contains(&a1)).unwrap();
        let region_a = &map.regions[region_a_idx];

        // Ensure a2 is in the same region
        assert!(region_a.members.contains(&a2));

        // Ensure b1, b2 are NOT in this region
        assert!(!region_a.members.contains(&b1));
        assert!(!region_a.members.contains(&b2));

        // Get the other region
        let region_b = &map.regions[1 - region_a_idx];
        assert!(region_b.members.contains(&b1));
        assert!(region_b.members.contains(&b2));
    }

    #[test]
    fn test_cartographer_empty_db() {
        let db = GallifreyDB::new().unwrap();
        let cartographer = Cartographer::new();
        let map = cartographer.generate_map(&db, "vec", 2).unwrap();
        assert_eq!(map.regions.len(), 0);
    }

    #[test]
    fn test_cartographer_dimension_mismatch() {
        let db = GallifreyDB::new().unwrap();
        db.create_node(
            "Point",
            PropertyMapBuilder::new()
                .insert_vector("vec", &[0.1, 0.1])
                .build()
        ).unwrap();
        db.create_node(
            "Point",
            PropertyMapBuilder::new()
                .insert_vector("vec", &[0.1, 0.1, 0.1]) // 3D
                .build()
        ).unwrap();

        let cartographer = Cartographer::new();
        let result = cartographer.generate_map(&db, "vec", 2);
        assert!(result.is_err());
    }
}
