//! Voyager: Semantic Random Walk Engine.
//!
//! "Follow the train of thought."
//!
//! Voyager generates random walks through the graph, where the probability of moving
//! to a neighbor is biased by semantic similarity. This simulates a "train of thought"
//! where the system naturally gravitates towards related concepts, but can occasionally
//! jump to less related ones based on a temperature parameter.
//!
//! # Concepts
//! - **Train of Thought**: A sequence of nodes generated by a semantic random walk.
//! - **Temperature**: Controls the randomness of the walk.
//!   - `T -> 0`: Highly deterministic, always picks the most semantically similar neighbor.
//!   - `T -> ∞`: Completely random walk, ignoring semantic similarity.
//!
//! # Use Cases
//! - **Synthetic Trajectories**: Generating realistic user browsing paths for testing.
//! - **Recommendation**: "Users who start here often end up thinking about this..."
//! - **Graph Embedding**: Generating node sequences for Node2Vec-style embeddings, but semantically biased.

use crate::AletheiaDB;
use crate::core::error::Result;
use crate::core::id::NodeId;
use crate::core::vector::ops::cosine_similarity;
use rand::prelude::*;

/// Configuration for a Voyager walk.
#[derive(Debug, Clone)]
pub struct WalkConfig {
    /// The vector property to use for semantic similarity.
    pub vector_property: String,
    /// The maximum length of the walk.
    pub max_steps: usize,
    /// The temperature of the softmax function.
    /// Lower values (e.g., 0.1) make the walk heavily biased towards similar nodes.
    /// Higher values (e.g., 10.0) make the walk more uniform (random).
    pub temperature: f32,
    /// The default similarity score to use if a node lacks a vector.
    pub missing_vector_similarity: f32,
}

impl Default for WalkConfig {
    fn default() -> Self {
        Self {
            vector_property: "embedding".to_string(),
            max_steps: 10,
            temperature: 1.0,
            missing_vector_similarity: 0.0, // Neutral/slightly penalizing default
        }
    }
}

/// The Voyager Engine.
pub struct Voyager<'a> {
    db: &'a AletheiaDB,
}

impl<'a> Voyager<'a> {
    /// Create a new Voyager instance.
    pub fn new(db: &'a AletheiaDB) -> Self {
        Self { db }
    }

    /// Generate a semantic "train of thought" walk starting from a seed node.
    pub fn generate_walk(&self, seed: NodeId, config: &WalkConfig) -> Result<Vec<NodeId>> {
        let mut walk = Vec::with_capacity(config.max_steps);
        walk.push(seed);

        let mut current = seed;
        let mut rng = rand::thread_rng();

        for _ in 1..config.max_steps {
            // Get current node's vector
            let current_node = self.db.get_node(current)?;
            let current_vec = current_node
                .properties
                .get(&config.vector_property)
                .and_then(|v| v.as_vector())
                .map(|v| v.to_vec());

            // Get outgoing neighbors
            let edges = self.db.get_outgoing_edges(current);
            if edges.is_empty() {
                break; // Dead end
            }

            let mut neighbors = Vec::with_capacity(edges.len());
            let mut similarities = Vec::with_capacity(edges.len());

            for edge_id in edges {
                if let Ok(target_id) = self.db.get_edge_target(edge_id) {
                    // Try to get neighbor's vector
                    let mut sim = config.missing_vector_similarity;
                    #[allow(clippy::collapsible_if)]
                    if let Some(ref c_vec) = current_vec {
                        if let Ok(target_node) = self.db.get_node(target_id) {
                            if let Some(t_vec) = target_node
                                .properties
                                .get(&config.vector_property)
                                .and_then(|v| v.as_vector())
                            {
                                if let Ok(s) = cosine_similarity(c_vec, t_vec) {
                                    // Similarity is [-1, 1], map to [0, 2] to avoid negative logits
                                    sim = s + 1.0;
                                }
                            }
                        }
                    }
                    neighbors.push(target_id);
                    similarities.push(sim);
                }
            }

            if neighbors.is_empty() {
                break;
            }

            // Apply softmax with temperature to calculate transition probabilities
            let next_node =
                self.pick_next_node(&neighbors, &similarities, config.temperature, &mut rng);
            walk.push(next_node);
            current = next_node;
        }

        Ok(walk)
    }

    /// Helper to pick the next node using softmax over similarities.
    fn pick_next_node(
        &self,
        neighbors: &[NodeId],
        similarities: &[f32],
        temperature: f32,
        rng: &mut ThreadRng,
    ) -> NodeId {
        let mut max_sim = f32::NEG_INFINITY;
        for &sim in similarities {
            if sim > max_sim {
                max_sim = sim;
            }
        }

        // Compute logits (sim / temperature)
        let mut weights = Vec::with_capacity(similarities.len());
        let mut sum_exp = 0.0;

        for &sim in similarities {
            // Subtract max for numerical stability
            let logit = (sim - max_sim) / temperature.max(0.01);
            let exp_val = logit.exp();
            weights.push(exp_val);
            sum_exp += exp_val;
        }

        // Normalize weights into probabilities
        let mut probabilities = Vec::with_capacity(weights.len());
        for w in weights {
            probabilities.push(w / sum_exp);
        }

        // Sample from the categorical distribution
        let rand_val: f32 = rng.r#gen();
        let mut cumulative = 0.0;

        for (i, &prob) in probabilities.iter().enumerate() {
            cumulative += prob;
            if rand_val <= cumulative {
                return neighbors[i];
            }
        }

        // Fallback (should rarely happen due to float precision)
        *neighbors.last().unwrap()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::PropertyMapBuilder;

    #[test]
    fn test_voyager_deterministic_walk_low_temp() {
        let db = AletheiaDB::new().unwrap();

        // Node A: [1.0, 0.0]
        // Node B: [1.0, 0.0] (Identical to A)
        // Node C: [0.0, 1.0] (Orthogonal to A)

        let props_a = PropertyMapBuilder::new()
            .insert_vector("vec", &[1.0, 0.0])
            .build();
        let a = db.create_node("Node", props_a).unwrap();

        let props_b = PropertyMapBuilder::new()
            .insert_vector("vec", &[1.0, 0.0])
            .build();
        let b = db.create_node("Node", props_b).unwrap();

        let props_c = PropertyMapBuilder::new()
            .insert_vector("vec", &[0.0, 1.0])
            .build();
        let c = db.create_node("Node", props_c).unwrap();

        // A -> B, A -> C
        db.create_edge(a, b, "NEXT", Default::default()).unwrap();
        db.create_edge(a, c, "NEXT", Default::default()).unwrap();

        let voyager = Voyager::new(&db);
        let config = WalkConfig {
            vector_property: "vec".to_string(),
            max_steps: 2,
            temperature: 0.01, // Very low temperature, should always pick B
            missing_vector_similarity: 0.0,
        };

        // Run multiple times to ensure it consistently picks B
        for _ in 0..10 {
            let walk = voyager.generate_walk(a, &config).unwrap();
            assert_eq!(walk.len(), 2);
            assert_eq!(walk[0], a);
            assert_eq!(
                walk[1], b,
                "Low temperature should reliably pick the most similar node"
            );
        }
    }

    #[test]
    fn test_voyager_explorative_walk_high_temp() {
        let db = AletheiaDB::new().unwrap();

        let props_a = PropertyMapBuilder::new()
            .insert_vector("vec", &[1.0, 0.0])
            .build();
        let a = db.create_node("Node", props_a).unwrap();

        let props_b = PropertyMapBuilder::new()
            .insert_vector("vec", &[1.0, 0.0])
            .build();
        let b = db.create_node("Node", props_b).unwrap();

        let props_c = PropertyMapBuilder::new()
            .insert_vector("vec", &[0.0, 1.0])
            .build();
        let c = db.create_node("Node", props_c).unwrap();

        // A -> B, A -> C
        db.create_edge(a, b, "NEXT", Default::default()).unwrap();
        db.create_edge(a, c, "NEXT", Default::default()).unwrap();

        let voyager = Voyager::new(&db);
        let config = WalkConfig {
            vector_property: "vec".to_string(),
            max_steps: 2,
            temperature: 100.0, // High temperature, should make probabilities nearly equal
            missing_vector_similarity: 0.0,
        };

        // We run multiple walks and count selections to verify both are reachable
        let mut b_count = 0;
        let mut c_count = 0;

        for _ in 0..100 {
            let walk = voyager.generate_walk(a, &config).unwrap();
            if walk[1] == b {
                b_count += 1;
            }
            if walk[1] == c {
                c_count += 1;
            }
        }

        // Should pick both some of the time, not just the similar one
        assert!(b_count > 10, "Explorative walk should pick B sometimes");
        assert!(c_count > 10, "Explorative walk should pick C sometimes");
    }
}
